name: Build and Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project version
        id: get_version
        run: echo "version=$(grep -oPm1 '(?<=<Version>)[^<]+' ./src/Api/Api.csproj)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/yet-another-garmin-connect-client-api:${{ steps.get_version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/yet-another-garmin-connect-client-api:latest